name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        make_target: [test, vet]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
      - name: Set build variables
        run: |
          echo "MAKE_TARGET=${{ matrix.make_target }}" >> $GITHUB_ENV

      - name: Run ${{matrix.make_target}}
        run: |
          make $MAKE_TARGET

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docscheck
        run: |
          make docscheck
